<?php

namespace Database\Seeders;

use App\Models\Lga;
use Illuminate\Database\Seeder;

class LgaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $lgas = array(
            array('id' => '1','state' => 'abia','state_id' => '1','lg_name' => 'Aba North'),
            array('id' => '2','state' => 'abia','state_id' => '1','lg_name' => 'Aba South'),
            array('id' => '3','state' => 'abia','state_id' => '1','lg_name' => 'Arochukwu'),
            array('id' => '4','state' => 'abia','state_id' => '1','lg_name' => 'Bende'),
            array('id' => '5','state' => 'abia','state_id' => '1','lg_name' => 'Ikwuano'),
            array('id' => '6','state' => 'abia','state_id' => '1','lg_name' => 'Isiala Ngwa North'),
            array('id' => '7','state' => 'abia','state_id' => '1','lg_name' => 'Isiala Ngwa South'),
            array('id' => '8','state' => 'abia','state_id' => '1','lg_name' => 'Isuikwuato'),
            array('id' => '9','state' => 'abia','state_id' => '1','lg_name' => 'Obi Ngwa'),
            array('id' => '10','state' => 'abia','state_id' => '1','lg_name' => 'Ohafia'),
            array('id' => '11','state' => 'abia','state_id' => '1','lg_name' => 'Osisioma'),
            array('id' => '12','state' => 'abia','state_id' => '1','lg_name' => 'Ugwunagbo'),
            array('id' => '13','state' => 'abia','state_id' => '1','lg_name' => 'Ukwa East'),
            array('id' => '14','state' => 'abia','state_id' => '1','lg_name' => 'Ukwa West'),
            array('id' => '15','state' => 'abia','state_id' => '1','lg_name' => 'Umuahia North'),
            array('id' => '16','state' => 'abia','state_id' => '1','lg_name' => 'Umuahia South'),
            array('id' => '17','state' => 'abia','state_id' => '1','lg_name' => 'Umu Nneochi'),
            array('id' => '18','state' => 'adamawa','state_id' => '2','lg_name' => 'Demsa'),
            array('id' => '19','state' => 'adamawa','state_id' => '2','lg_name' => 'Fufure'),
            array('id' => '20','state' => 'adamawa','state_id' => '2','lg_name' => 'Ganye'),
            array('id' => '21','state' => 'adamawa','state_id' => '2','lg_name' => 'Gayuk'),
            array('id' => '22','state' => 'adamawa','state_id' => '2','lg_name' => 'Gombi'),
            array('id' => '23','state' => 'adamawa','state_id' => '2','lg_name' => 'Grie'),
            array('id' => '24','state' => 'adamawa','state_id' => '2','lg_name' => 'Hong'),
            array('id' => '25','state' => 'adamawa','state_id' => '2','lg_name' => 'Jada'),
            array('id' => '26','state' => 'adamawa','state_id' => '2','lg_name' => 'Lamurde'),
            array('id' => '27','state' => 'adamawa','state_id' => '2','lg_name' => 'Madagali'),
            array('id' => '28','state' => 'adamawa','state_id' => '2','lg_name' => 'Maiha'),
            array('id' => '29','state' => 'adamawa','state_id' => '2','lg_name' => 'Mayo Belwa'),
            array('id' => '30','state' => 'adamawa','state_id' => '2','lg_name' => 'Michika'),
            array('id' => '31','state' => 'adamawa','state_id' => '2','lg_name' => 'Mubi North'),
            array('id' => '32','state' => 'adamawa','state_id' => '2','lg_name' => 'Mubi South'),
            array('id' => '33','state' => 'adamawa','state_id' => '2','lg_name' => 'Numan'),
            array('id' => '34','state' => 'adamawa','state_id' => '2','lg_name' => 'Shelleng'),
            array('id' => '35','state' => 'adamawa','state_id' => '2','lg_name' => 'Song'),
            array('id' => '36','state' => 'adamawa','state_id' => '2','lg_name' => 'Toungo'),
            array('id' => '37','state' => 'adamawa','state_id' => '2','lg_name' => 'Yola North'),
            array('id' => '38','state' => 'adamawa','state_id' => '2','lg_name' => 'Yola South'),
            array('id' => '39','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Abak'),
            array('id' => '40','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Eastern Obolo'),
            array('id' => '41','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Eket'),
            array('id' => '42','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Esit Eket'),
            array('id' => '43','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Essien Udim'),
            array('id' => '44','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Etim Ekpo'),
            array('id' => '45','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Etinan'),
            array('id' => '46','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Ibeno'),
            array('id' => '47','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Ibesikpo Asutan'),
            array('id' => '48','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Ibiono-Ibom'),
            array('id' => '49','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Ika'),
            array('id' => '50','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Ikono'),
            array('id' => '51','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Ikot Abasi'),
            array('id' => '52','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Ikot Ekpene'),
            array('id' => '53','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Ini'),
            array('id' => '54','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Itu'),
            array('id' => '55','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Mbo'),
            array('id' => '56','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Mkpat-Enin'),
            array('id' => '57','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Nsit-Atai'),
            array('id' => '58','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Nsit-Ibom'),
            array('id' => '59','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Nsit-Ubium'),
            array('id' => '60','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Obot Akara'),
            array('id' => '61','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Okobo'),
            array('id' => '62','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Onna'),
            array('id' => '63','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Oron'),
            array('id' => '64','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Oruk Anam'),
            array('id' => '65','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Udung-Uko'),
            array('id' => '66','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Ukanafun'),
            array('id' => '67','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Uruan'),
            array('id' => '68','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Urue-Offong/Oruko'),
            array('id' => '69','state' => 'akwa-ibom','state_id' => '3','lg_name' => 'Uyo'),
            array('id' => '70','state' => 'anambra','state_id' => '4','lg_name' => 'Aguata'),
            array('id' => '71','state' => 'anambra','state_id' => '4','lg_name' => 'Anambra East'),
            array('id' => '72','state' => 'anambra','state_id' => '4','lg_name' => 'Anambra West'),
            array('id' => '73','state' => 'anambra','state_id' => '4','lg_name' => 'Anaocha'),
            array('id' => '74','state' => 'anambra','state_id' => '4','lg_name' => 'Awka North'),
            array('id' => '75','state' => 'anambra','state_id' => '4','lg_name' => 'Awka South'),
            array('id' => '76','state' => 'anambra','state_id' => '4','lg_name' => 'Ayamelum'),
            array('id' => '77','state' => 'anambra','state_id' => '4','lg_name' => 'Dunukofia'),
            array('id' => '78','state' => 'anambra','state_id' => '4','lg_name' => 'Ekwusigo'),
            array('id' => '79','state' => 'anambra','state_id' => '4','lg_name' => 'Idemili North'),
            array('id' => '80','state' => 'anambra','state_id' => '4','lg_name' => 'Idemili South'),
            array('id' => '81','state' => 'anambra','state_id' => '4','lg_name' => 'Ihiala'),
            array('id' => '82','state' => 'anambra','state_id' => '4','lg_name' => 'Njikoka'),
            array('id' => '83','state' => 'anambra','state_id' => '4','lg_name' => 'Nnewi North'),
            array('id' => '84','state' => 'anambra','state_id' => '4','lg_name' => 'Nnewi South'),
            array('id' => '85','state' => 'anambra','state_id' => '4','lg_name' => 'Ogbaru'),
            array('id' => '86','state' => 'anambra','state_id' => '4','lg_name' => 'Onitsha North'),
            array('id' => '87','state' => 'anambra','state_id' => '4','lg_name' => 'Onitsha South'),
            array('id' => '88','state' => 'anambra','state_id' => '4','lg_name' => 'Orumba North'),
            array('id' => '89','state' => 'anambra','state_id' => '4','lg_name' => 'Orumba South'),
            array('id' => '90','state' => 'anambra','state_id' => '4','lg_name' => 'Oyi'),
            array('id' => '91','state' => 'bauchi','state_id' => '5','lg_name' => 'Alkaleri'),
            array('id' => '92','state' => 'bauchi','state_id' => '5','lg_name' => 'Bauchi'),
            array('id' => '93','state' => 'bauchi','state_id' => '5','lg_name' => 'Bogoro'),
            array('id' => '94','state' => 'bauchi','state_id' => '5','lg_name' => 'Damban'),
            array('id' => '95','state' => 'bauchi','state_id' => '5','lg_name' => 'Darazo'),
            array('id' => '96','state' => 'bauchi','state_id' => '5','lg_name' => 'Dass'),
            array('id' => '97','state' => 'bauchi','state_id' => '5','lg_name' => 'Gamawa'),
            array('id' => '98','state' => 'bauchi','state_id' => '5','lg_name' => 'Ganjuwa'),
            array('id' => '99','state' => 'bauchi','state_id' => '5','lg_name' => 'Giade'),
            array('id' => '100','state' => 'bauchi','state_id' => '5','lg_name' => 'Itas/Gadau'),
            array('id' => '101','state' => 'bauchi','state_id' => '5','lg_name' => 'Jama\'are'),
            array('id' => '102','state' => 'bauchi','state_id' => '5','lg_name' => 'Katagum'),
            array('id' => '103','state' => 'bauchi','state_id' => '5','lg_name' => 'Kirfi'),
            array('id' => '104','state' => 'bauchi','state_id' => '5','lg_name' => 'Misau'),
            array('id' => '105','state' => 'bauchi','state_id' => '5','lg_name' => 'Ningi'),
            array('id' => '106','state' => 'bauchi','state_id' => '5','lg_name' => 'Shira'),
            array('id' => '107','state' => 'bauchi','state_id' => '5','lg_name' => 'Tafawa Balewa'),
            array('id' => '108','state' => 'bauchi','state_id' => '5','lg_name' => 'Toro'),
            array('id' => '109','state' => 'bauchi','state_id' => '5','lg_name' => 'Warji'),
            array('id' => '110','state' => 'bauchi','state_id' => '5','lg_name' => 'Zaki'),
            array('id' => '111','state' => 'bayelsa','state_id' => '6','lg_name' => 'Brass'),
            array('id' => '112','state' => 'bayelsa','state_id' => '6','lg_name' => 'Ekeremor'),
            array('id' => '113','state' => 'bayelsa','state_id' => '6','lg_name' => 'Kolokuma/Opokuma'),
            array('id' => '114','state' => 'bayelsa','state_id' => '6','lg_name' => 'Nembe'),
            array('id' => '115','state' => 'bayelsa','state_id' => '6','lg_name' => 'Ogbia'),
            array('id' => '116','state' => 'bayelsa','state_id' => '6','lg_name' => 'Sagbama'),
            array('id' => '117','state' => 'bayelsa','state_id' => '6','lg_name' => 'Southern Ijaw'),
            array('id' => '118','state' => 'bayelsa','state_id' => '6','lg_name' => 'Yenagoa'),
            array('id' => '119','state' => 'benue','state_id' => '7','lg_name' => 'Agatu'),
            array('id' => '120','state' => 'benue','state_id' => '7','lg_name' => 'Apa'),
            array('id' => '121','state' => 'benue','state_id' => '7','lg_name' => 'Ado'),
            array('id' => '122','state' => 'benue','state_id' => '7','lg_name' => 'Buruku'),
            array('id' => '123','state' => 'benue','state_id' => '7','lg_name' => 'Gboko'),
            array('id' => '124','state' => 'benue','state_id' => '7','lg_name' => 'Guma'),
            array('id' => '125','state' => 'benue','state_id' => '7','lg_name' => 'Gwer East'),
            array('id' => '126','state' => 'benue','state_id' => '7','lg_name' => 'Gwer West'),
            array('id' => '127','state' => 'benue','state_id' => '7','lg_name' => 'Katsina-Ala'),
            array('id' => '128','state' => 'benue','state_id' => '7','lg_name' => 'Konshisha'),
            array('id' => '129','state' => 'benue','state_id' => '7','lg_name' => 'Kwande'),
            array('id' => '130','state' => 'benue','state_id' => '7','lg_name' => 'Logo'),
            array('id' => '131','state' => 'benue','state_id' => '7','lg_name' => 'Makurdi'),
            array('id' => '132','state' => 'benue','state_id' => '7','lg_name' => 'Obi'),
            array('id' => '133','state' => 'benue','state_id' => '7','lg_name' => 'Ogbadibo'),
            array('id' => '134','state' => 'benue','state_id' => '7','lg_name' => 'Ohimini'),
            array('id' => '135','state' => 'benue','state_id' => '7','lg_name' => 'Oju'),
            array('id' => '136','state' => 'benue','state_id' => '7','lg_name' => 'Okpokwu'),
            array('id' => '137','state' => 'benue','state_id' => '7','lg_name' => 'Oturkpo'),
            array('id' => '138','state' => 'benue','state_id' => '7','lg_name' => 'Tarka'),
            array('id' => '139','state' => 'benue','state_id' => '7','lg_name' => 'Ukum'),
            array('id' => '140','state' => 'benue','state_id' => '7','lg_name' => 'Ushongo'),
            array('id' => '141','state' => 'benue','state_id' => '7','lg_name' => 'Vandeikya'),
            array('id' => '142','state' => 'borno','state_id' => '8','lg_name' => 'Abadam'),
            array('id' => '143','state' => 'borno','state_id' => '8','lg_name' => 'Askira/Uba'),
            array('id' => '144','state' => 'borno','state_id' => '8','lg_name' => 'Bama'),
            array('id' => '145','state' => 'borno','state_id' => '8','lg_name' => 'Bayo'),
            array('id' => '146','state' => 'borno','state_id' => '8','lg_name' => 'Biu'),
            array('id' => '147','state' => 'borno','state_id' => '8','lg_name' => 'Chibok'),
            array('id' => '148','state' => 'borno','state_id' => '8','lg_name' => 'Damboa'),
            array('id' => '149','state' => 'borno','state_id' => '8','lg_name' => 'Dikwa'),
            array('id' => '150','state' => 'borno','state_id' => '8','lg_name' => 'Gubio'),
            array('id' => '151','state' => 'borno','state_id' => '8','lg_name' => 'Guzamala'),
            array('id' => '152','state' => 'borno','state_id' => '8','lg_name' => 'Gwoza'),
            array('id' => '153','state' => 'borno','state_id' => '8','lg_name' => 'Hawul'),
            array('id' => '154','state' => 'borno','state_id' => '8','lg_name' => 'Jere'),
            array('id' => '155','state' => 'borno','state_id' => '8','lg_name' => 'Kaga'),
            array('id' => '156','state' => 'borno','state_id' => '8','lg_name' => 'Kala/Balge'),
            array('id' => '157','state' => 'borno','state_id' => '8','lg_name' => 'Konduga'),
            array('id' => '158','state' => 'borno','state_id' => '8','lg_name' => 'Kukawa'),
            array('id' => '159','state' => 'borno','state_id' => '8','lg_name' => 'Kwaya Kusar'),
            array('id' => '160','state' => 'borno','state_id' => '8','lg_name' => 'Mafa'),
            array('id' => '161','state' => 'borno','state_id' => '8','lg_name' => 'Magumeri'),
            array('id' => '162','state' => 'borno','state_id' => '8','lg_name' => 'Maiduguri'),
            array('id' => '163','state' => 'borno','state_id' => '8','lg_name' => 'Marte'),
            array('id' => '164','state' => 'borno','state_id' => '8','lg_name' => 'Mobbar'),
            array('id' => '165','state' => 'borno','state_id' => '8','lg_name' => 'Monguno'),
            array('id' => '166','state' => 'borno','state_id' => '8','lg_name' => 'Ngala'),
            array('id' => '167','state' => 'borno','state_id' => '8','lg_name' => 'Nganzai'),
            array('id' => '168','state' => 'borno','state_id' => '8','lg_name' => 'Shani'),
            array('id' => '169','state' => 'cross-river','state_id' => '9','lg_name' => 'Abi'),
            array('id' => '170','state' => 'cross-river','state_id' => '9','lg_name' => 'Akamkpa'),
            array('id' => '171','state' => 'cross-river','state_id' => '9','lg_name' => 'Akpabuyo'),
            array('id' => '172','state' => 'cross-river','state_id' => '9','lg_name' => 'Bakassi'),
            array('id' => '173','state' => 'cross-river','state_id' => '9','lg_name' => 'Bekwarra'),
            array('id' => '174','state' => 'cross-river','state_id' => '9','lg_name' => 'Biase'),
            array('id' => '175','state' => 'cross-river','state_id' => '9','lg_name' => 'Boki'),
            array('id' => '176','state' => 'cross-river','state_id' => '9','lg_name' => 'Calabar Municipal'),
            array('id' => '177','state' => 'cross-river','state_id' => '9','lg_name' => 'Calabar South'),
            array('id' => '178','state' => 'cross-river','state_id' => '9','lg_name' => 'Etung'),
            array('id' => '179','state' => 'cross-river','state_id' => '9','lg_name' => 'Ikom'),
            array('id' => '180','state' => 'cross-river','state_id' => '9','lg_name' => 'Obanliku'),
            array('id' => '181','state' => 'cross-river','state_id' => '9','lg_name' => 'Obubra'),
            array('id' => '182','state' => 'cross-river','state_id' => '9','lg_name' => 'Obudu'),
            array('id' => '183','state' => 'cross-river','state_id' => '9','lg_name' => 'Odukpani'),
            array('id' => '184','state' => 'cross-river','state_id' => '9','lg_name' => 'Ogoja'),
            array('id' => '185','state' => 'cross-river','state_id' => '9','lg_name' => 'Yakuur'),
            array('id' => '186','state' => 'cross-river','state_id' => '9','lg_name' => 'Yala'),
            array('id' => '187','state' => 'delta','state_id' => '10','lg_name' => 'Aniocha North'),
            array('id' => '188','state' => 'delta','state_id' => '10','lg_name' => 'Aniocha South'),
            array('id' => '189','state' => 'delta','state_id' => '10','lg_name' => 'Bomadi'),
            array('id' => '190','state' => 'delta','state_id' => '10','lg_name' => 'Burutu'),
            array('id' => '191','state' => 'delta','state_id' => '10','lg_name' => 'Ethiope East'),
            array('id' => '192','state' => 'delta','state_id' => '10','lg_name' => 'Ethiope West'),
            array('id' => '193','state' => 'delta','state_id' => '10','lg_name' => 'Ika North East'),
            array('id' => '194','state' => 'delta','state_id' => '10','lg_name' => 'Ika South'),
            array('id' => '195','state' => 'delta','state_id' => '10','lg_name' => 'Isoko North'),
            array('id' => '196','state' => 'delta','state_id' => '10','lg_name' => 'Isoko South'),
            array('id' => '197','state' => 'delta','state_id' => '10','lg_name' => 'Ndokwa East'),
            array('id' => '198','state' => 'delta','state_id' => '10','lg_name' => 'Ndokwa West'),
            array('id' => '199','state' => 'delta','state_id' => '10','lg_name' => 'Okpe'),
            array('id' => '200','state' => 'delta','state_id' => '10','lg_name' => 'Oshimili North'),
            array('id' => '201','state' => 'delta','state_id' => '10','lg_name' => 'Oshimili South'),
            array('id' => '202','state' => 'delta','state_id' => '10','lg_name' => 'Patani'),
            array('id' => '203','state' => 'delta','state_id' => '10','lg_name' => 'Sapele'),
            array('id' => '204','state' => 'delta','state_id' => '10','lg_name' => 'Udu'),
            array('id' => '205','state' => 'delta','state_id' => '10','lg_name' => 'Ughelli North'),
            array('id' => '206','state' => 'delta','state_id' => '10','lg_name' => 'Ughelli South'),
            array('id' => '207','state' => 'delta','state_id' => '10','lg_name' => 'Ukwuani'),
            array('id' => '208','state' => 'delta','state_id' => '10','lg_name' => 'Uvwie'),
            array('id' => '209','state' => 'delta','state_id' => '10','lg_name' => 'Warri North'),
            array('id' => '210','state' => 'delta','state_id' => '10','lg_name' => 'Warri South'),
            array('id' => '211','state' => 'delta','state_id' => '10','lg_name' => 'Warri South West'),
            array('id' => '212','state' => 'ebonyi','state_id' => '11','lg_name' => 'Abakaliki'),
            array('id' => '213','state' => 'ebonyi','state_id' => '11','lg_name' => 'Afikpo North'),
            array('id' => '214','state' => 'ebonyi','state_id' => '11','lg_name' => 'Afikpo South Edda'),
            array('id' => '215','state' => 'ebonyi','state_id' => '11','lg_name' => 'Ebonyi'),
            array('id' => '216','state' => 'ebonyi','state_id' => '11','lg_name' => 'Ezza North'),
            array('id' => '217','state' => 'ebonyi','state_id' => '11','lg_name' => 'Ezza South'),
            array('id' => '218','state' => 'ebonyi','state_id' => '11','lg_name' => 'Ikwo'),
            array('id' => '219','state' => 'ebonyi','state_id' => '11','lg_name' => 'Ishielu'),
            array('id' => '220','state' => 'ebonyi','state_id' => '11','lg_name' => 'Ivo'),
            array('id' => '221','state' => 'ebonyi','state_id' => '11','lg_name' => 'Izzi'),
            array('id' => '222','state' => 'ebonyi','state_id' => '11','lg_name' => 'Ohaozara'),
            array('id' => '223','state' => 'ebonyi','state_id' => '11','lg_name' => 'Ohaukwu'),
            array('id' => '224','state' => 'ebonyi','state_id' => '11','lg_name' => 'Onicha'),
            array('id' => '225','state' => 'edo','state_id' => '12','lg_name' => 'Akoko-Edo'),
            array('id' => '226','state' => 'edo','state_id' => '12','lg_name' => 'Egor'),
            array('id' => '227','state' => 'edo','state_id' => '12','lg_name' => 'Esan Central'),
            array('id' => '228','state' => 'edo','state_id' => '12','lg_name' => 'Esan North-East'),
            array('id' => '229','state' => 'edo','state_id' => '12','lg_name' => 'Esan South-East'),
            array('id' => '230','state' => 'edo','state_id' => '12','lg_name' => 'Esan West'),
            array('id' => '231','state' => 'edo','state_id' => '12','lg_name' => 'Etsako Central'),
            array('id' => '232','state' => 'edo','state_id' => '12','lg_name' => 'Etsako East'),
            array('id' => '233','state' => 'edo','state_id' => '12','lg_name' => 'Etsako West'),
            array('id' => '234','state' => 'edo','state_id' => '12','lg_name' => 'Igueben'),
            array('id' => '235','state' => 'edo','state_id' => '12','lg_name' => 'Ikpoba Okha'),
            array('id' => '236','state' => 'edo','state_id' => '12','lg_name' => 'Orhionmwon'),
            array('id' => '237','state' => 'edo','state_id' => '12','lg_name' => 'Oredo'),
            array('id' => '238','state' => 'edo','state_id' => '12','lg_name' => 'Ovia North-East'),
            array('id' => '239','state' => 'edo','state_id' => '12','lg_name' => 'Ovia South-West'),
            array('id' => '240','state' => 'edo','state_id' => '12','lg_name' => 'Owan East'),
            array('id' => '241','state' => 'edo','state_id' => '12','lg_name' => 'Owan West'),
            array('id' => '242','state' => 'edo','state_id' => '12','lg_name' => 'Uhunmwonde'),
            array('id' => '243','state' => 'ekiti','state_id' => '13','lg_name' => 'Ado Ekiti'),
            array('id' => '244','state' => 'ekiti','state_id' => '13','lg_name' => 'Efon'),
            array('id' => '245','state' => 'ekiti','state_id' => '13','lg_name' => 'Ekiti East'),
            array('id' => '246','state' => 'ekiti','state_id' => '13','lg_name' => 'Ekiti South-West'),
            array('id' => '247','state' => 'ekiti','state_id' => '13','lg_name' => 'Ekiti West'),
            array('id' => '248','state' => 'ekiti','state_id' => '13','lg_name' => 'Emure'),
            array('id' => '249','state' => 'ekiti','state_id' => '13','lg_name' => 'Gbonyin'),
            array('id' => '250','state' => 'ekiti','state_id' => '13','lg_name' => 'Ido Osi'),
            array('id' => '251','state' => 'ekiti','state_id' => '13','lg_name' => 'Ijero'),
            array('id' => '252','state' => 'ekiti','state_id' => '13','lg_name' => 'Ikere'),
            array('id' => '253','state' => 'ekiti','state_id' => '13','lg_name' => 'Ikole'),
            array('id' => '254','state' => 'ekiti','state_id' => '13','lg_name' => 'Ilejemeje'),
            array('id' => '255','state' => 'ekiti','state_id' => '13','lg_name' => 'Irepodun/Ifelodun'),
            array('id' => '256','state' => 'ekiti','state_id' => '13','lg_name' => 'Ise/Orun'),
            array('id' => '257','state' => 'ekiti','state_id' => '13','lg_name' => 'Moba'),
            array('id' => '258','state' => 'ekiti','state_id' => '13','lg_name' => 'Oye'),
            array('id' => '259','state' => 'enugu','state_id' => '14','lg_name' => 'Udi'),
            array('id' => '260','state' => 'enugu','state_id' => '14','lg_name' => 'Aninri'),
            array('id' => '261','state' => 'enugu','state_id' => '14','lg_name' => 'Awgu'),
            array('id' => '262','state' => 'enugu','state_id' => '14','lg_name' => 'Enugu East'),
            array('id' => '263','state' => 'enugu','state_id' => '14','lg_name' => 'Enugu North'),
            array('id' => '264','state' => 'enugu','state_id' => '14','lg_name' => 'Enugu South'),
            array('id' => '265','state' => 'enugu','state_id' => '14','lg_name' => 'Ezeagu'),
            array('id' => '266','state' => 'enugu','state_id' => '14','lg_name' => 'Igbo Etiti'),
            array('id' => '267','state' => 'enugu','state_id' => '14','lg_name' => 'Igbo Eze North'),
            array('id' => '268','state' => 'enugu','state_id' => '14','lg_name' => 'Igbo Eze South'),
            array('id' => '269','state' => 'enugu','state_id' => '14','lg_name' => 'Isi Uzo'),
            array('id' => '270','state' => 'enugu','state_id' => '14','lg_name' => 'Nkanu East'),
            array('id' => '271','state' => 'enugu','state_id' => '14','lg_name' => 'Nkanu West'),
            array('id' => '272','state' => 'enugu','state_id' => '14','lg_name' => 'Nsukka'),
            array('id' => '273','state' => 'enugu','state_id' => '14','lg_name' => 'Oji River'),
            array('id' => '274','state' => 'enugu','state_id' => '14','lg_name' => 'Udenu'),
            array('id' => '275','state' => 'enugu','state_id' => '14','lg_name' => 'Uzo-Uwani'),
            array('id' => '276','state' => 'fct','state_id' => '15','lg_name' => 'Abaji'),
            array('id' => '277','state' => 'fct','state_id' => '15','lg_name' => 'Bwari'),
            array('id' => '278','state' => 'fct','state_id' => '15','lg_name' => 'Gwagwalada'),
            array('id' => '279','state' => 'fct','state_id' => '15','lg_name' => 'Kuje'),
            array('id' => '280','state' => 'fct','state_id' => '15','lg_name' => 'Kwali'),
            array('id' => '281','state' => 'fct','state_id' => '15','lg_name' => 'Municipal Area Council'),
            array('id' => '282','state' => 'gombe','state_id' => '16','lg_name' => 'Akko'),
            array('id' => '283','state' => 'gombe','state_id' => '16','lg_name' => 'Balanga'),
            array('id' => '284','state' => 'gombe','state_id' => '16','lg_name' => 'Billiri'),
            array('id' => '285','state' => 'gombe','state_id' => '16','lg_name' => 'Dukku'),
            array('id' => '286','state' => 'gombe','state_id' => '16','lg_name' => 'Funakaye'),
            array('id' => '287','state' => 'gombe','state_id' => '16','lg_name' => 'Gombe'),
            array('id' => '288','state' => 'gombe','state_id' => '16','lg_name' => 'Kaltungo'),
            array('id' => '289','state' => 'gombe','state_id' => '16','lg_name' => 'Kwami'),
            array('id' => '290','state' => 'gombe','state_id' => '16','lg_name' => 'Nafada'),
            array('id' => '291','state' => 'gombe','state_id' => '16','lg_name' => 'Shongom'),
            array('id' => '292','state' => 'gombe','state_id' => '16','lg_name' => 'Yamaltu/Deba'),
            array('id' => '293','state' => 'imo','state_id' => '17','lg_name' => 'Aboh Mbaise'),
            array('id' => '294','state' => 'imo','state_id' => '17','lg_name' => 'Ahiazu Mbaise'),
            array('id' => '295','state' => 'imo','state_id' => '17','lg_name' => 'Ehime Mbano'),
            array('id' => '296','state' => 'imo','state_id' => '17','lg_name' => 'Ezinihitte'),
            array('id' => '297','state' => 'imo','state_id' => '17','lg_name' => 'Ideato North'),
            array('id' => '298','state' => 'imo','state_id' => '17','lg_name' => 'Ideato South'),
            array('id' => '299','state' => 'imo','state_id' => '17','lg_name' => 'Ihitte/Uboma'),
            array('id' => '300','state' => 'imo','state_id' => '17','lg_name' => 'Ikeduru'),
            array('id' => '301','state' => 'imo','state_id' => '17','lg_name' => 'Isiala Mbano'),
            array('id' => '302','state' => 'imo','state_id' => '17','lg_name' => 'Isu'),
            array('id' => '303','state' => 'imo','state_id' => '17','lg_name' => 'Mbaitoli'),
            array('id' => '304','state' => 'imo','state_id' => '17','lg_name' => 'Ngor Okpala'),
            array('id' => '305','state' => 'imo','state_id' => '17','lg_name' => 'Njaba'),
            array('id' => '306','state' => 'imo','state_id' => '17','lg_name' => 'Nkwerre'),
            array('id' => '307','state' => 'imo','state_id' => '17','lg_name' => 'Nwangele'),
            array('id' => '308','state' => 'imo','state_id' => '17','lg_name' => 'Obowo'),
            array('id' => '309','state' => 'imo','state_id' => '17','lg_name' => 'Oguta'),
            array('id' => '310','state' => 'imo','state_id' => '17','lg_name' => 'Ohaji/Egbema'),
            array('id' => '311','state' => 'imo','state_id' => '17','lg_name' => 'Okigwe'),
            array('id' => '312','state' => 'imo','state_id' => '17','lg_name' => 'Orlu'),
            array('id' => '313','state' => 'imo','state_id' => '17','lg_name' => 'Orsu'),
            array('id' => '314','state' => 'imo','state_id' => '17','lg_name' => 'Oru East'),
            array('id' => '315','state' => 'imo','state_id' => '17','lg_name' => 'Oru West'),
            array('id' => '316','state' => 'imo','state_id' => '17','lg_name' => 'Owerri Municipal'),
            array('id' => '317','state' => 'imo','state_id' => '17','lg_name' => 'Owerri North'),
            array('id' => '318','state' => 'imo','state_id' => '17','lg_name' => 'Owerri West'),
            array('id' => '319','state' => 'imo','state_id' => '17','lg_name' => 'Unuimo'),
            array('id' => '320','state' => 'jigawa','state_id' => '18','lg_name' => 'Auyo'),
            array('id' => '321','state' => 'jigawa','state_id' => '18','lg_name' => 'Babura'),
            array('id' => '322','state' => 'jigawa','state_id' => '18','lg_name' => 'Biriniwa'),
            array('id' => '323','state' => 'jigawa','state_id' => '18','lg_name' => 'Birnin Kudu'),
            array('id' => '324','state' => 'jigawa','state_id' => '18','lg_name' => 'Buji'),
            array('id' => '325','state' => 'jigawa','state_id' => '18','lg_name' => 'Dutse'),
            array('id' => '326','state' => 'jigawa','state_id' => '18','lg_name' => 'Gagarawa'),
            array('id' => '327','state' => 'jigawa','state_id' => '18','lg_name' => 'Garki'),
            array('id' => '328','state' => 'jigawa','state_id' => '18','lg_name' => 'Gumel'),
            array('id' => '329','state' => 'jigawa','state_id' => '18','lg_name' => 'Guri'),
            array('id' => '330','state' => 'jigawa','state_id' => '18','lg_name' => 'Gwaram'),
            array('id' => '331','state' => 'jigawa','state_id' => '18','lg_name' => 'Gwiwa'),
            array('id' => '332','state' => 'jigawa','state_id' => '18','lg_name' => 'Hadejia'),
            array('id' => '333','state' => 'jigawa','state_id' => '18','lg_name' => 'Jahun'),
            array('id' => '334','state' => 'jigawa','state_id' => '18','lg_name' => 'Kafin Hausa'),
            array('id' => '335','state' => 'jigawa','state_id' => '18','lg_name' => 'Kazaure'),
            array('id' => '336','state' => 'jigawa','state_id' => '18','lg_name' => 'Kiri Kasama'),
            array('id' => '337','state' => 'jigawa','state_id' => '18','lg_name' => 'Kiyawa'),
            array('id' => '338','state' => 'jigawa','state_id' => '18','lg_name' => 'Kaugama'),
            array('id' => '339','state' => 'jigawa','state_id' => '18','lg_name' => 'Maigatari'),
            array('id' => '340','state' => 'jigawa','state_id' => '18','lg_name' => 'Malam Madori'),
            array('id' => '341','state' => 'jigawa','state_id' => '18','lg_name' => 'Miga'),
            array('id' => '342','state' => 'jigawa','state_id' => '18','lg_name' => 'Ringim'),
            array('id' => '343','state' => 'jigawa','state_id' => '18','lg_name' => 'Roni'),
            array('id' => '344','state' => 'jigawa','state_id' => '18','lg_name' => 'Sule Tankarkar'),
            array('id' => '345','state' => 'jigawa','state_id' => '18','lg_name' => 'Taura'),
            array('id' => '346','state' => 'jigawa','state_id' => '18','lg_name' => 'Yankwashi'),
            array('id' => '347','state' => 'kaduna','state_id' => '19','lg_name' => 'Birnin Gwari'),
            array('id' => '348','state' => 'kaduna','state_id' => '19','lg_name' => 'Chikun'),
            array('id' => '349','state' => 'kaduna','state_id' => '19','lg_name' => 'Giwa'),
            array('id' => '350','state' => 'kaduna','state_id' => '19','lg_name' => 'Igabi'),
            array('id' => '351','state' => 'kaduna','state_id' => '19','lg_name' => 'Ikara'),
            array('id' => '352','state' => 'kaduna','state_id' => '19','lg_name' => 'Jaba'),
            array('id' => '353','state' => 'kaduna','state_id' => '19','lg_name' => 'Jema\'a'),
            array('id' => '354','state' => 'kaduna','state_id' => '19','lg_name' => 'Kachia'),
            array('id' => '355','state' => 'kaduna','state_id' => '19','lg_name' => 'Kaduna North'),
            array('id' => '356','state' => 'kaduna','state_id' => '19','lg_name' => 'Kaduna South'),
            array('id' => '357','state' => 'kaduna','state_id' => '19','lg_name' => 'Kagarko'),
            array('id' => '358','state' => 'kaduna','state_id' => '19','lg_name' => 'Kajuru'),
            array('id' => '359','state' => 'kaduna','state_id' => '19','lg_name' => 'Kaura'),
            array('id' => '360','state' => 'kaduna','state_id' => '19','lg_name' => 'Kauru'),
            array('id' => '361','state' => 'kaduna','state_id' => '19','lg_name' => 'Kubau'),
            array('id' => '362','state' => 'kaduna','state_id' => '19','lg_name' => 'Kudan'),
            array('id' => '363','state' => 'kaduna','state_id' => '19','lg_name' => 'Lere'),
            array('id' => '364','state' => 'kaduna','state_id' => '19','lg_name' => 'Makarfi'),
            array('id' => '365','state' => 'kaduna','state_id' => '19','lg_name' => 'Sabon Gari'),
            array('id' => '366','state' => 'kaduna','state_id' => '19','lg_name' => 'Sanga'),
            array('id' => '367','state' => 'kaduna','state_id' => '19','lg_name' => 'Soba'),
            array('id' => '368','state' => 'kaduna','state_id' => '19','lg_name' => 'Zangon Kataf'),
            array('id' => '369','state' => 'kaduna','state_id' => '19','lg_name' => 'Zaria'),
            array('id' => '370','state' => 'kano','state_id' => '20','lg_name' => 'Ajingi'),
            array('id' => '371','state' => 'kano','state_id' => '20','lg_name' => 'Albasu'),
            array('id' => '372','state' => 'kano','state_id' => '20','lg_name' => 'Bagwai'),
            array('id' => '373','state' => 'kano','state_id' => '20','lg_name' => 'Bebeji'),
            array('id' => '374','state' => 'kano','state_id' => '20','lg_name' => 'Bichi'),
            array('id' => '375','state' => 'kano','state_id' => '20','lg_name' => 'Bunkure'),
            array('id' => '376','state' => 'kano','state_id' => '20','lg_name' => 'Dala'),
            array('id' => '377','state' => 'kano','state_id' => '20','lg_name' => 'Dambatta'),
            array('id' => '378','state' => 'kano','state_id' => '20','lg_name' => 'Dawakin Kudu'),
            array('id' => '379','state' => 'kano','state_id' => '20','lg_name' => 'Dawakin Tofa'),
            array('id' => '380','state' => 'kano','state_id' => '20','lg_name' => 'Doguwa'),
            array('id' => '381','state' => 'kano','state_id' => '20','lg_name' => 'Fagge'),
            array('id' => '382','state' => 'kano','state_id' => '20','lg_name' => 'Gabasawa'),
            array('id' => '383','state' => 'kano','state_id' => '20','lg_name' => 'Garko'),
            array('id' => '384','state' => 'kano','state_id' => '20','lg_name' => 'Garun Mallam'),
            array('id' => '385','state' => 'kano','state_id' => '20','lg_name' => 'Gaya'),
            array('id' => '386','state' => 'kano','state_id' => '20','lg_name' => 'Gezawa'),
            array('id' => '387','state' => 'kano','state_id' => '20','lg_name' => 'Gwale'),
            array('id' => '388','state' => 'kano','state_id' => '20','lg_name' => 'Gwarzo'),
            array('id' => '389','state' => 'kano','state_id' => '20','lg_name' => 'Kabo'),
            array('id' => '390','state' => 'kano','state_id' => '20','lg_name' => 'Kano Municipal'),
            array('id' => '391','state' => 'kano','state_id' => '20','lg_name' => 'Karaye'),
            array('id' => '392','state' => 'kano','state_id' => '20','lg_name' => 'Kibiya'),
            array('id' => '393','state' => 'kano','state_id' => '20','lg_name' => 'Kiru'),
            array('id' => '394','state' => 'kano','state_id' => '20','lg_name' => 'Kumbotso'),
            array('id' => '395','state' => 'kano','state_id' => '20','lg_name' => 'Kunchi'),
            array('id' => '396','state' => 'kano','state_id' => '20','lg_name' => 'Kura'),
            array('id' => '397','state' => 'kano','state_id' => '20','lg_name' => 'Madobi'),
            array('id' => '398','state' => 'kano','state_id' => '20','lg_name' => 'Makoda'),
            array('id' => '399','state' => 'kano','state_id' => '20','lg_name' => 'Minjibir'),
            array('id' => '400','state' => 'kano','state_id' => '20','lg_name' => 'Nasarawa'),
            array('id' => '401','state' => 'kano','state_id' => '20','lg_name' => 'Rano'),
            array('id' => '402','state' => 'kano','state_id' => '20','lg_name' => 'Rimin Gado'),
            array('id' => '403','state' => 'kano','state_id' => '20','lg_name' => 'Rogo'),
            array('id' => '404','state' => 'kano','state_id' => '20','lg_name' => 'Shanono'),
            array('id' => '405','state' => 'kano','state_id' => '20','lg_name' => 'Sumaila'),
            array('id' => '406','state' => 'kano','state_id' => '20','lg_name' => 'Takai'),
            array('id' => '407','state' => 'kano','state_id' => '20','lg_name' => 'Tarauni'),
            array('id' => '408','state' => 'kano','state_id' => '20','lg_name' => 'Tofa'),
            array('id' => '409','state' => 'kano','state_id' => '20','lg_name' => 'Tsanyawa'),
            array('id' => '410','state' => 'kano','state_id' => '20','lg_name' => 'Tudun Wada'),
            array('id' => '411','state' => 'kano','state_id' => '20','lg_name' => 'Ungogo'),
            array('id' => '412','state' => 'kano','state_id' => '20','lg_name' => 'Warawa'),
            array('id' => '413','state' => 'kano','state_id' => '20','lg_name' => 'Wudil'),
            array('id' => '414','state' => 'katsina','state_id' => '21','lg_name' => 'Bakori'),
            array('id' => '415','state' => 'katsina','state_id' => '21','lg_name' => 'Batagarawa'),
            array('id' => '416','state' => 'katsina','state_id' => '21','lg_name' => 'Batsari'),
            array('id' => '417','state' => 'katsina','state_id' => '21','lg_name' => 'Baure'),
            array('id' => '418','state' => 'katsina','state_id' => '21','lg_name' => 'Bindawa'),
            array('id' => '419','state' => 'katsina','state_id' => '21','lg_name' => 'Charanchi'),
            array('id' => '420','state' => 'katsina','state_id' => '21','lg_name' => 'Dandume'),
            array('id' => '421','state' => 'katsina','state_id' => '21','lg_name' => 'Danja'),
            array('id' => '422','state' => 'katsina','state_id' => '21','lg_name' => 'Dan Musa'),
            array('id' => '423','state' => 'katsina','state_id' => '21','lg_name' => 'Daura'),
            array('id' => '424','state' => 'katsina','state_id' => '21','lg_name' => 'Dutsi'),
            array('id' => '425','state' => 'katsina','state_id' => '21','lg_name' => 'Dutsin Ma'),
            array('id' => '426','state' => 'katsina','state_id' => '21','lg_name' => 'Faskari'),
            array('id' => '427','state' => 'katsina','state_id' => '21','lg_name' => 'Funtua'),
            array('id' => '428','state' => 'katsina','state_id' => '21','lg_name' => 'Ingawa'),
            array('id' => '429','state' => 'katsina','state_id' => '21','lg_name' => 'Jibia'),
            array('id' => '430','state' => 'katsina','state_id' => '21','lg_name' => 'Kafur'),
            array('id' => '431','state' => 'katsina','state_id' => '21','lg_name' => 'Kaita'),
            array('id' => '432','state' => 'katsina','state_id' => '21','lg_name' => 'Kankara'),
            array('id' => '433','state' => 'katsina','state_id' => '21','lg_name' => 'Kankia'),
            array('id' => '434','state' => 'katsina','state_id' => '21','lg_name' => 'Katsina'),
            array('id' => '435','state' => 'katsina','state_id' => '21','lg_name' => 'Kurfi'),
            array('id' => '436','state' => 'katsina','state_id' => '21','lg_name' => 'Kusada'),
            array('id' => '437','state' => 'katsina','state_id' => '21','lg_name' => 'Mai\'Adua'),
            array('id' => '438','state' => 'katsina','state_id' => '21','lg_name' => 'Malumfashi'),
            array('id' => '439','state' => 'katsina','state_id' => '21','lg_name' => 'Mani'),
            array('id' => '440','state' => 'katsina','state_id' => '21','lg_name' => 'Mashi'),
            array('id' => '441','state' => 'katsina','state_id' => '21','lg_name' => 'Matazu'),
            array('id' => '442','state' => 'katsina','state_id' => '21','lg_name' => 'Musawa'),
            array('id' => '443','state' => 'katsina','state_id' => '21','lg_name' => 'Rimi'),
            array('id' => '444','state' => 'katsina','state_id' => '21','lg_name' => 'Sabuwa'),
            array('id' => '445','state' => 'katsina','state_id' => '21','lg_name' => 'Safana'),
            array('id' => '446','state' => 'katsina','state_id' => '21','lg_name' => 'Sandamu'),
            array('id' => '447','state' => 'katsina','state_id' => '21','lg_name' => 'Zango'),
            array('id' => '448','state' => 'kebbi','state_id' => '22','lg_name' => 'Aleiro'),
            array('id' => '449','state' => 'kebbi','state_id' => '22','lg_name' => 'Arewa Dandi'),
            array('id' => '450','state' => 'kebbi','state_id' => '22','lg_name' => 'Argungu'),
            array('id' => '451','state' => 'kebbi','state_id' => '22','lg_name' => 'Augie'),
            array('id' => '452','state' => 'kebbi','state_id' => '22','lg_name' => 'Bagudo'),
            array('id' => '453','state' => 'kebbi','state_id' => '22','lg_name' => 'Birnin Kebbi'),
            array('id' => '454','state' => 'kebbi','state_id' => '22','lg_name' => 'Bunza'),
            array('id' => '455','state' => 'kebbi','state_id' => '22','lg_name' => 'Dandi'),
            array('id' => '456','state' => 'kebbi','state_id' => '22','lg_name' => 'Fakai'),
            array('id' => '457','state' => 'kebbi','state_id' => '22','lg_name' => 'Gwandu'),
            array('id' => '458','state' => 'kebbi','state_id' => '22','lg_name' => 'Jega'),
            array('id' => '459','state' => 'kebbi','state_id' => '22','lg_name' => 'Kalgo'),
            array('id' => '460','state' => 'kebbi','state_id' => '22','lg_name' => 'Koko/Besse'),
            array('id' => '461','state' => 'kebbi','state_id' => '22','lg_name' => 'Maiyama'),
            array('id' => '462','state' => 'kebbi','state_id' => '22','lg_name' => 'Ngaski'),
            array('id' => '463','state' => 'kebbi','state_id' => '22','lg_name' => 'Sakaba'),
            array('id' => '464','state' => 'kebbi','state_id' => '22','lg_name' => 'Shanga'),
            array('id' => '465','state' => 'kebbi','state_id' => '22','lg_name' => 'Suru'),
            array('id' => '466','state' => 'kebbi','state_id' => '22','lg_name' => 'Wasagu/Danko'),
            array('id' => '467','state' => 'kebbi','state_id' => '22','lg_name' => 'Yauri'),
            array('id' => '468','state' => 'kebbi','state_id' => '22','lg_name' => 'Zuru'),
            array('id' => '469','state' => 'kogi','state_id' => '23','lg_name' => 'Adavi'),
            array('id' => '470','state' => 'kogi','state_id' => '23','lg_name' => 'Ajaokuta'),
            array('id' => '471','state' => 'kogi','state_id' => '23','lg_name' => 'Ankpa'),
            array('id' => '472','state' => 'kogi','state_id' => '23','lg_name' => 'Bassa'),
            array('id' => '473','state' => 'kogi','state_id' => '23','lg_name' => 'Dekina'),
            array('id' => '474','state' => 'kogi','state_id' => '23','lg_name' => 'Ibaji'),
            array('id' => '475','state' => 'kogi','state_id' => '23','lg_name' => 'Idah'),
            array('id' => '476','state' => 'kogi','state_id' => '23','lg_name' => 'Igalamela Odolu'),
            array('id' => '477','state' => 'kogi','state_id' => '23','lg_name' => 'Ijumu'),
            array('id' => '478','state' => 'kogi','state_id' => '23','lg_name' => 'Kabba/Bunu'),
            array('id' => '479','state' => 'kogi','state_id' => '23','lg_name' => 'Kogi'),
            array('id' => '480','state' => 'kogi','state_id' => '23','lg_name' => 'Lokoja'),
            array('id' => '481','state' => 'kogi','state_id' => '23','lg_name' => 'Mopa Muro'),
            array('id' => '482','state' => 'kogi','state_id' => '23','lg_name' => 'Ofu'),
            array('id' => '483','state' => 'kogi','state_id' => '23','lg_name' => 'Ogori/Magongo'),
            array('id' => '484','state' => 'kogi','state_id' => '23','lg_name' => 'Okehi'),
            array('id' => '485','state' => 'kogi','state_id' => '23','lg_name' => 'Okene'),
            array('id' => '486','state' => 'kogi','state_id' => '23','lg_name' => 'Olamaboro'),
            array('id' => '487','state' => 'kogi','state_id' => '23','lg_name' => 'Omala'),
            array('id' => '488','state' => 'kogi','state_id' => '23','lg_name' => 'Yagba East'),
            array('id' => '489','state' => 'kogi','state_id' => '23','lg_name' => 'Yagba West'),
            array('id' => '490','state' => 'kwara','state_id' => '24','lg_name' => 'Asa'),
            array('id' => '491','state' => 'kwara','state_id' => '24','lg_name' => 'Baruten'),
            array('id' => '492','state' => 'kwara','state_id' => '24','lg_name' => 'Edu'),
            array('id' => '493','state' => 'kwara','state_id' => '24','lg_name' => 'Ekiti'),
            array('id' => '494','state' => 'kwara','state_id' => '24','lg_name' => 'Ifelodun'),
            array('id' => '495','state' => 'kwara','state_id' => '24','lg_name' => 'Ilorin East'),
            array('id' => '496','state' => 'kwara','state_id' => '24','lg_name' => 'Ilorin South'),
            array('id' => '497','state' => 'kwara','state_id' => '24','lg_name' => 'Ilorin West'),
            array('id' => '498','state' => 'kwara','state_id' => '24','lg_name' => 'Irepodun'),
            array('id' => '499','state' => 'kwara','state_id' => '24','lg_name' => 'Isin'),
            array('id' => '500','state' => 'kwara','state_id' => '24','lg_name' => 'Kaiama'),
            array('id' => '501','state' => 'kwara','state_id' => '24','lg_name' => 'Moro'),
            array('id' => '502','state' => 'kwara','state_id' => '24','lg_name' => 'Offa'),
            array('id' => '503','state' => 'kwara','state_id' => '24','lg_name' => 'Oke Ero'),
            array('id' => '504','state' => 'kwara','state_id' => '24','lg_name' => 'Oyun'),
            array('id' => '505','state' => 'kwara','state_id' => '24','lg_name' => 'Pategi'),
            array('id' => '506','state' => 'lagos','state_id' => '25','lg_name' => 'Agege'),
            array('id' => '507','state' => 'lagos','state_id' => '25','lg_name' => 'Ajeromi-Ifelodun'),
            array('id' => '508','state' => 'lagos','state_id' => '25','lg_name' => 'Alimosho'),
            array('id' => '509','state' => 'lagos','state_id' => '25','lg_name' => 'Amuwo-Odofin'),
            array('id' => '510','state' => 'lagos','state_id' => '25','lg_name' => 'Apapa'),
            array('id' => '511','state' => 'lagos','state_id' => '25','lg_name' => 'Badagry'),
            array('id' => '512','state' => 'lagos','state_id' => '25','lg_name' => 'Epe'),
            array('id' => '513','state' => 'lagos','state_id' => '25','lg_name' => 'Eti Osa'),
            array('id' => '514','state' => 'lagos','state_id' => '25','lg_name' => 'Ibeju-Lekki'),
            array('id' => '515','state' => 'lagos','state_id' => '25','lg_name' => 'Ifako-Ijaiye'),
            array('id' => '516','state' => 'lagos','state_id' => '25','lg_name' => 'Ikeja'),
            array('id' => '517','state' => 'lagos','state_id' => '25','lg_name' => 'Ikorodu'),
            array('id' => '518','state' => 'lagos','state_id' => '25','lg_name' => 'Kosofe'),
            array('id' => '519','state' => 'lagos','state_id' => '25','lg_name' => 'Lagos Island'),
            array('id' => '520','state' => 'lagos','state_id' => '25','lg_name' => 'Lagos Mainland'),
            array('id' => '521','state' => 'lagos','state_id' => '25','lg_name' => 'Mushin'),
            array('id' => '522','state' => 'lagos','state_id' => '25','lg_name' => 'Ojo'),
            array('id' => '523','state' => 'lagos','state_id' => '25','lg_name' => 'Oshodi-Isolo'),
            array('id' => '524','state' => 'lagos','state_id' => '25','lg_name' => 'Shomolu'),
            array('id' => '525','state' => 'lagos','state_id' => '25','lg_name' => 'Surulere'),
            array('id' => '526','state' => 'nasarawa','state_id' => '26','lg_name' => 'Akwanga'),
            array('id' => '527','state' => 'nasarawa','state_id' => '26','lg_name' => 'Awe'),
            array('id' => '528','state' => 'nasarawa','state_id' => '26','lg_name' => 'Doma'),
            array('id' => '529','state' => 'nasarawa','state_id' => '26','lg_name' => 'Karu'),
            array('id' => '530','state' => 'nasarawa','state_id' => '26','lg_name' => 'Keana'),
            array('id' => '531','state' => 'nasarawa','state_id' => '26','lg_name' => 'Keffi'),
            array('id' => '532','state' => 'nasarawa','state_id' => '26','lg_name' => 'Kokona'),
            array('id' => '533','state' => 'nasarawa','state_id' => '26','lg_name' => 'Lafia'),
            array('id' => '534','state' => 'nasarawa','state_id' => '26','lg_name' => 'Nasarawa'),
            array('id' => '535','state' => 'nasarawa','state_id' => '26','lg_name' => 'Nasarawa Egon'),
            array('id' => '536','state' => 'nasarawa','state_id' => '26','lg_name' => 'Obi'),
            array('id' => '537','state' => 'nasarawa','state_id' => '26','lg_name' => 'Toto'),
            array('id' => '538','state' => 'nasarawa','state_id' => '26','lg_name' => 'Wamba'),
            array('id' => '539','state' => 'niger','state_id' => '27','lg_name' => 'Agaie'),
            array('id' => '540','state' => 'niger','state_id' => '27','lg_name' => 'Agwara'),
            array('id' => '541','state' => 'niger','state_id' => '27','lg_name' => 'Bida'),
            array('id' => '542','state' => 'niger','state_id' => '27','lg_name' => 'Borgu'),
            array('id' => '543','state' => 'niger','state_id' => '27','lg_name' => 'Bosso'),
            array('id' => '544','state' => 'niger','state_id' => '27','lg_name' => 'Chanchaga'),
            array('id' => '545','state' => 'niger','state_id' => '27','lg_name' => 'Edati'),
            array('id' => '546','state' => 'niger','state_id' => '27','lg_name' => 'Gbako'),
            array('id' => '547','state' => 'niger','state_id' => '27','lg_name' => 'Gurara'),
            array('id' => '548','state' => 'niger','state_id' => '27','lg_name' => 'Katcha'),
            array('id' => '549','state' => 'niger','state_id' => '27','lg_name' => 'Kontagora'),
            array('id' => '550','state' => 'niger','state_id' => '27','lg_name' => 'Lapai'),
            array('id' => '551','state' => 'niger','state_id' => '27','lg_name' => 'Lavun'),
            array('id' => '552','state' => 'niger','state_id' => '27','lg_name' => 'Magama'),
            array('id' => '553','state' => 'niger','state_id' => '27','lg_name' => 'Mariga'),
            array('id' => '554','state' => 'niger','state_id' => '27','lg_name' => 'Mashegu'),
            array('id' => '555','state' => 'niger','state_id' => '27','lg_name' => 'Mokwa'),
            array('id' => '556','state' => 'niger','state_id' => '27','lg_name' => 'Moya'),
            array('id' => '557','state' => 'niger','state_id' => '27','lg_name' => 'Paikoro'),
            array('id' => '558','state' => 'niger','state_id' => '27','lg_name' => 'Rafi'),
            array('id' => '559','state' => 'niger','state_id' => '27','lg_name' => 'Rijau'),
            array('id' => '560','state' => 'niger','state_id' => '27','lg_name' => 'Shiroro'),
            array('id' => '561','state' => 'niger','state_id' => '27','lg_name' => 'Suleja'),
            array('id' => '562','state' => 'niger','state_id' => '27','lg_name' => 'Tafa'),
            array('id' => '563','state' => 'niger','state_id' => '27','lg_name' => 'Wushishi'),
            array('id' => '564','state' => 'ogun','state_id' => '28','lg_name' => 'Abeokuta North'),
            array('id' => '565','state' => 'ogun','state_id' => '28','lg_name' => 'Abeokuta South'),
            array('id' => '566','state' => 'ogun','state_id' => '28','lg_name' => 'Ado-Odo/Ota'),
            array('id' => '567','state' => 'ogun','state_id' => '28','lg_name' => 'Yewa North'),
            array('id' => '568','state' => 'ogun','state_id' => '28','lg_name' => 'Yewa South'),
            array('id' => '569','state' => 'ogun','state_id' => '28','lg_name' => 'Ewekoro'),
            array('id' => '570','state' => 'ogun','state_id' => '28','lg_name' => 'Ifo'),
            array('id' => '571','state' => 'ogun','state_id' => '28','lg_name' => 'Ijebu East'),
            array('id' => '572','state' => 'ogun','state_id' => '28','lg_name' => 'Ijebu North'),
            array('id' => '573','state' => 'ogun','state_id' => '28','lg_name' => 'Ijebu North East'),
            array('id' => '574','state' => 'ogun','state_id' => '28','lg_name' => 'Ijebu Ode'),
            array('id' => '575','state' => 'ogun','state_id' => '28','lg_name' => 'Ikenne'),
            array('id' => '576','state' => 'ogun','state_id' => '28','lg_name' => 'Imeko Afon'),
            array('id' => '577','state' => 'ogun','state_id' => '28','lg_name' => 'Ipokia'),
            array('id' => '578','state' => 'ogun','state_id' => '28','lg_name' => 'Obafemi Owode'),
            array('id' => '579','state' => 'ogun','state_id' => '28','lg_name' => 'Odeda'),
            array('id' => '580','state' => 'ogun','state_id' => '28','lg_name' => 'Odogbolu'),
            array('id' => '581','state' => 'ogun','state_id' => '28','lg_name' => 'Ogun Waterside'),
            array('id' => '582','state' => 'ogun','state_id' => '28','lg_name' => 'Remo North'),
            array('id' => '583','state' => 'ogun','state_id' => '28','lg_name' => 'Shagamu'),
            array('id' => '584','state' => 'ondo','state_id' => '29','lg_name' => 'Akoko North-East'),
            array('id' => '585','state' => 'ondo','state_id' => '29','lg_name' => 'Akoko North-West'),
            array('id' => '586','state' => 'ondo','state_id' => '29','lg_name' => 'Akoko South-West'),
            array('id' => '587','state' => 'ondo','state_id' => '29','lg_name' => 'Akoko South-East'),
            array('id' => '588','state' => 'ondo','state_id' => '29','lg_name' => 'Akure North'),
            array('id' => '589','state' => 'ondo','state_id' => '29','lg_name' => 'Akure South'),
            array('id' => '590','state' => 'ondo','state_id' => '29','lg_name' => 'Ese Odo'),
            array('id' => '591','state' => 'ondo','state_id' => '29','lg_name' => 'Idanre'),
            array('id' => '592','state' => 'ondo','state_id' => '29','lg_name' => 'Ifedore'),
            array('id' => '593','state' => 'ondo','state_id' => '29','lg_name' => 'Ilaje'),
            array('id' => '594','state' => 'ondo','state_id' => '29','lg_name' => 'Ile Oluji/Okeigbo'),
            array('id' => '595','state' => 'ondo','state_id' => '29','lg_name' => 'Irele'),
            array('id' => '596','state' => 'ondo','state_id' => '29','lg_name' => 'Odigbo'),
            array('id' => '597','state' => 'ondo','state_id' => '29','lg_name' => 'Okitipupa'),
            array('id' => '598','state' => 'ondo','state_id' => '29','lg_name' => 'Ondo East'),
            array('id' => '599','state' => 'ondo','state_id' => '29','lg_name' => 'Ondo West'),
            array('id' => '600','state' => 'ondo','state_id' => '29','lg_name' => 'Ose'),
            array('id' => '601','state' => 'ondo','state_id' => '29','lg_name' => 'Owo'),
            array('id' => '602','state' => 'osun','state_id' => '30','lg_name' => 'Osogbo'),
            array('id' => '603','state' => 'osun','state_id' => '30','lg_name' => 'Atakunmosa East'),
            array('id' => '604','state' => 'osun','state_id' => '30','lg_name' => 'Atakunmosa West'),
            array('id' => '605','state' => 'osun','state_id' => '30','lg_name' => 'Aiyedaade'),
            array('id' => '606','state' => 'osun','state_id' => '30','lg_name' => 'Aiyedire'),
            array('id' => '607','state' => 'osun','state_id' => '30','lg_name' => 'Boluwaduro'),
            array('id' => '608','state' => 'osun','state_id' => '30','lg_name' => 'Boripe'),
            array('id' => '609','state' => 'osun','state_id' => '30','lg_name' => 'Ede North'),
            array('id' => '610','state' => 'osun','state_id' => '30','lg_name' => 'Ede South'),
            array('id' => '611','state' => 'osun','state_id' => '30','lg_name' => 'Ife Central'),
            array('id' => '612','state' => 'osun','state_id' => '30','lg_name' => 'Ife East'),
            array('id' => '613','state' => 'osun','state_id' => '30','lg_name' => 'Ife North'),
            array('id' => '614','state' => 'osun','state_id' => '30','lg_name' => 'Ife South'),
            array('id' => '615','state' => 'osun','state_id' => '30','lg_name' => 'Egbedore'),
            array('id' => '616','state' => 'osun','state_id' => '30','lg_name' => 'Ejigbo'),
            array('id' => '617','state' => 'osun','state_id' => '30','lg_name' => 'Ifedayo'),
            array('id' => '618','state' => 'osun','state_id' => '30','lg_name' => 'Ifelodun'),
            array('id' => '619','state' => 'osun','state_id' => '30','lg_name' => 'Ila'),
            array('id' => '620','state' => 'osun','state_id' => '30','lg_name' => 'Ilesa East'),
            array('id' => '621','state' => 'osun','state_id' => '30','lg_name' => 'Ilesa West'),
            array('id' => '622','state' => 'osun','state_id' => '30','lg_name' => 'Irepodun'),
            array('id' => '623','state' => 'osun','state_id' => '30','lg_name' => 'Irewole'),
            array('id' => '624','state' => 'osun','state_id' => '30','lg_name' => 'Isokan'),
            array('id' => '625','state' => 'osun','state_id' => '30','lg_name' => 'Iwo'),
            array('id' => '626','state' => 'osun','state_id' => '30','lg_name' => 'Obokun'),
            array('id' => '627','state' => 'osun','state_id' => '30','lg_name' => 'Odo Otin'),
            array('id' => '628','state' => 'osun','state_id' => '30','lg_name' => 'Ola Oluwa'),
            array('id' => '629','state' => 'osun','state_id' => '30','lg_name' => 'Olorunda'),
            array('id' => '630','state' => 'osun','state_id' => '30','lg_name' => 'Oriade'),
            array('id' => '631','state' => 'osun','state_id' => '30','lg_name' => 'Orolu'),
            array('id' => '632','state' => 'oyo','state_id' => '31','lg_name' => 'Afijio'),
            array('id' => '633','state' => 'oyo','state_id' => '31','lg_name' => 'Akinyele'),
            array('id' => '634','state' => 'oyo','state_id' => '31','lg_name' => 'Atiba'),
            array('id' => '635','state' => 'oyo','state_id' => '31','lg_name' => 'Atisbo'),
            array('id' => '636','state' => 'oyo','state_id' => '31','lg_name' => 'Egbeda'),
            array('id' => '637','state' => 'oyo','state_id' => '31','lg_name' => 'Ibadan North'),
            array('id' => '638','state' => 'oyo','state_id' => '31','lg_name' => 'Ibadan North-East'),
            array('id' => '639','state' => 'oyo','state_id' => '31','lg_name' => 'Ibadan North-West'),
            array('id' => '640','state' => 'oyo','state_id' => '31','lg_name' => 'Ibadan South-East'),
            array('id' => '641','state' => 'oyo','state_id' => '31','lg_name' => 'Ibadan South-West'),
            array('id' => '642','state' => 'oyo','state_id' => '31','lg_name' => 'Ibarapa Central'),
            array('id' => '643','state' => 'oyo','state_id' => '31','lg_name' => 'Ibarapa East'),
            array('id' => '644','state' => 'oyo','state_id' => '31','lg_name' => 'Ibarapa North'),
            array('id' => '645','state' => 'oyo','state_id' => '31','lg_name' => 'Ido'),
            array('id' => '646','state' => 'oyo','state_id' => '31','lg_name' => 'Irepo'),
            array('id' => '647','state' => 'oyo','state_id' => '31','lg_name' => 'Iseyin'),
            array('id' => '648','state' => 'oyo','state_id' => '31','lg_name' => 'Itesiwaju'),
            array('id' => '649','state' => 'oyo','state_id' => '31','lg_name' => 'Iwajowa'),
            array('id' => '650','state' => 'oyo','state_id' => '31','lg_name' => 'Kajola'),
            array('id' => '651','state' => 'oyo','state_id' => '31','lg_name' => 'Lagelu'),
            array('id' => '652','state' => 'oyo','state_id' => '31','lg_name' => 'Ogbomosho North'),
            array('id' => '653','state' => 'oyo','state_id' => '31','lg_name' => 'Ogbomosho South'),
            array('id' => '654','state' => 'oyo','state_id' => '31','lg_name' => 'Ogo Oluwa'),
            array('id' => '655','state' => 'oyo','state_id' => '31','lg_name' => 'Olorunsogo'),
            array('id' => '656','state' => 'oyo','state_id' => '31','lg_name' => 'Oluyole'),
            array('id' => '657','state' => 'oyo','state_id' => '31','lg_name' => 'Ona Ara'),
            array('id' => '658','state' => 'oyo','state_id' => '31','lg_name' => 'Orelope'),
            array('id' => '659','state' => 'oyo','state_id' => '31','lg_name' => 'Ori Ire'),
            array('id' => '660','state' => 'oyo','state_id' => '31','lg_name' => 'Oyo West'),
            array('id' => '661','state' => 'oyo','state_id' => '31','lg_name' => 'Oyo East'),
            array('id' => '662','state' => 'oyo','state_id' => '31','lg_name' => 'Saki East'),
            array('id' => '663','state' => 'oyo','state_id' => '31','lg_name' => 'Saki West'),
            array('id' => '664','state' => 'oyo','state_id' => '31','lg_name' => 'Surulere'),
            array('id' => '665','state' => 'plateau','state_id' => '32','lg_name' => 'Bokkos'),
            array('id' => '666','state' => 'plateau','state_id' => '32','lg_name' => 'Barkin Ladi'),
            array('id' => '667','state' => 'plateau','state_id' => '32','lg_name' => 'Bassa'),
            array('id' => '668','state' => 'plateau','state_id' => '32','lg_name' => 'Jos East'),
            array('id' => '669','state' => 'plateau','state_id' => '32','lg_name' => 'Jos North'),
            array('id' => '670','state' => 'plateau','state_id' => '32','lg_name' => 'Jos South'),
            array('id' => '671','state' => 'plateau','state_id' => '32','lg_name' => 'Kanam'),
            array('id' => '672','state' => 'plateau','state_id' => '32','lg_name' => 'Kanke'),
            array('id' => '673','state' => 'plateau','state_id' => '32','lg_name' => 'Langtang South'),
            array('id' => '674','state' => 'plateau','state_id' => '32','lg_name' => 'Langtang North'),
            array('id' => '675','state' => 'plateau','state_id' => '32','lg_name' => 'Mangu'),
            array('id' => '676','state' => 'plateau','state_id' => '32','lg_name' => 'Mikang'),
            array('id' => '677','state' => 'plateau','state_id' => '32','lg_name' => 'Pankshin'),
            array('id' => '678','state' => 'plateau','state_id' => '32','lg_name' => 'Qua\'an Pan'),
            array('id' => '679','state' => 'plateau','state_id' => '32','lg_name' => 'Riyom'),
            array('id' => '680','state' => 'plateau','state_id' => '32','lg_name' => 'Shendam'),
            array('id' => '681','state' => 'plateau','state_id' => '32','lg_name' => 'Wase'),
            array('id' => '682','state' => 'rivers','state_id' => '33','lg_name' => 'Abua/Odual'),
            array('id' => '683','state' => 'rivers','state_id' => '33','lg_name' => 'Ahoada East'),
            array('id' => '684','state' => 'rivers','state_id' => '33','lg_name' => 'Ahoada West'),
            array('id' => '685','state' => 'rivers','state_id' => '33','lg_name' => 'Akuku-Toru'),
            array('id' => '686','state' => 'rivers','state_id' => '33','lg_name' => 'Andoni'),
            array('id' => '687','state' => 'rivers','state_id' => '33','lg_name' => 'Asari-Toru'),
            array('id' => '688','state' => 'rivers','state_id' => '33','lg_name' => 'Bonny'),
            array('id' => '689','state' => 'rivers','state_id' => '33','lg_name' => 'Degema'),
            array('id' => '690','state' => 'rivers','state_id' => '33','lg_name' => 'Eleme'),
            array('id' => '691','state' => 'rivers','state_id' => '33','lg_name' => 'Emuoha'),
            array('id' => '692','state' => 'rivers','state_id' => '33','lg_name' => 'Etche'),
            array('id' => '693','state' => 'rivers','state_id' => '33','lg_name' => 'Gokana'),
            array('id' => '694','state' => 'rivers','state_id' => '33','lg_name' => 'Ikwerre'),
            array('id' => '695','state' => 'rivers','state_id' => '33','lg_name' => 'Khana'),
            array('id' => '696','state' => 'rivers','state_id' => '33','lg_name' => 'Obio/Akpor'),
            array('id' => '697','state' => 'rivers','state_id' => '33','lg_name' => 'Ogu/Bolo'),
            array('id' => '698','state' => 'rivers','state_id' => '33','lg_name' => 'Ogba/Egbema/Ndoni'),
            array('id' => '699','state' => 'rivers','state_id' => '33','lg_name' => 'Okrika'),
            array('id' => '700','state' => 'rivers','state_id' => '33','lg_name' => 'Omuma'),
            array('id' => '701','state' => 'rivers','state_id' => '33','lg_name' => 'Opobo/Nkoro'),
            array('id' => '702','state' => 'rivers','state_id' => '33','lg_name' => 'Oyigbo'),
            array('id' => '703','state' => 'rivers','state_id' => '33','lg_name' => 'Port Harcourt'),
            array('id' => '704','state' => 'rivers','state_id' => '33','lg_name' => 'Tai'),
            array('id' => '705','state' => 'sokoto','state_id' => '34','lg_name' => 'Binji'),
            array('id' => '706','state' => 'sokoto','state_id' => '34','lg_name' => 'Dange Shuni'),
            array('id' => '707','state' => 'sokoto','state_id' => '34','lg_name' => 'Bodinga'),
            array('id' => '708','state' => 'sokoto','state_id' => '34','lg_name' => 'Gada'),
            array('id' => '709','state' => 'sokoto','state_id' => '34','lg_name' => 'Goronyo'),
            array('id' => '710','state' => 'sokoto','state_id' => '34','lg_name' => 'Gudu'),
            array('id' => '711','state' => 'sokoto','state_id' => '34','lg_name' => 'Gwadabawa'),
            array('id' => '712','state' => 'sokoto','state_id' => '34','lg_name' => 'Illela'),
            array('id' => '713','state' => 'sokoto','state_id' => '34','lg_name' => 'Isa'),
            array('id' => '714','state' => 'sokoto','state_id' => '34','lg_name' => 'Kebbe'),
            array('id' => '715','state' => 'sokoto','state_id' => '34','lg_name' => 'Kware'),
            array('id' => '716','state' => 'sokoto','state_id' => '34','lg_name' => 'Rabah'),
            array('id' => '717','state' => 'sokoto','state_id' => '34','lg_name' => 'Sabon Birni'),
            array('id' => '718','state' => 'sokoto','state_id' => '34','lg_name' => 'Shagari'),
            array('id' => '719','state' => 'sokoto','state_id' => '34','lg_name' => 'Silame'),
            array('id' => '720','state' => 'sokoto','state_id' => '34','lg_name' => 'Sokoto North'),
            array('id' => '721','state' => 'sokoto','state_id' => '34','lg_name' => 'Sokoto South'),
            array('id' => '722','state' => 'sokoto','state_id' => '34','lg_name' => 'Tambuwal'),
            array('id' => '723','state' => 'sokoto','state_id' => '34','lg_name' => 'Tangaza'),
            array('id' => '724','state' => 'sokoto','state_id' => '34','lg_name' => 'Tureta'),
            array('id' => '725','state' => 'sokoto','state_id' => '34','lg_name' => 'Wamako'),
            array('id' => '726','state' => 'sokoto','state_id' => '34','lg_name' => 'Wurno'),
            array('id' => '727','state' => 'sokoto','state_id' => '34','lg_name' => 'Yabo'),
            array('id' => '728','state' => 'taraba','state_id' => '35','lg_name' => 'Ardo Kola'),
            array('id' => '729','state' => 'taraba','state_id' => '35','lg_name' => 'Bali'),
            array('id' => '730','state' => 'taraba','state_id' => '35','lg_name' => 'Donga'),
            array('id' => '731','state' => 'taraba','state_id' => '35','lg_name' => 'Gashaka'),
            array('id' => '732','state' => 'taraba','state_id' => '35','lg_name' => 'Gassol'),
            array('id' => '733','state' => 'taraba','state_id' => '35','lg_name' => 'Ibi'),
            array('id' => '734','state' => 'taraba','state_id' => '35','lg_name' => 'Jalingo'),
            array('id' => '735','state' => 'taraba','state_id' => '35','lg_name' => 'Karim Lamido'),
            array('id' => '736','state' => 'taraba','state_id' => '35','lg_name' => 'Kumi'),
            array('id' => '737','state' => 'taraba','state_id' => '35','lg_name' => 'Lau'),
            array('id' => '738','state' => 'taraba','state_id' => '35','lg_name' => 'Sardauna'),
            array('id' => '739','state' => 'taraba','state_id' => '35','lg_name' => 'Takum'),
            array('id' => '740','state' => 'taraba','state_id' => '35','lg_name' => 'Ussa'),
            array('id' => '741','state' => 'taraba','state_id' => '35','lg_name' => 'Wukari'),
            array('id' => '742','state' => 'taraba','state_id' => '35','lg_name' => 'Yorro'),
            array('id' => '743','state' => 'taraba','state_id' => '35','lg_name' => 'Zing'),
            array('id' => '744','state' => 'yobe','state_id' => '36','lg_name' => 'Bade'),
            array('id' => '745','state' => 'yobe','state_id' => '36','lg_name' => 'Bursari'),
            array('id' => '746','state' => 'yobe','state_id' => '36','lg_name' => 'Damaturu'),
            array('id' => '747','state' => 'yobe','state_id' => '36','lg_name' => 'Fika'),
            array('id' => '748','state' => 'yobe','state_id' => '36','lg_name' => 'Fune'),
            array('id' => '749','state' => 'yobe','state_id' => '36','lg_name' => 'Geidam'),
            array('id' => '750','state' => 'yobe','state_id' => '36','lg_name' => 'Gujba'),
            array('id' => '751','state' => 'yobe','state_id' => '36','lg_name' => 'Gulani'),
            array('id' => '752','state' => 'yobe','state_id' => '36','lg_name' => 'Jakusko'),
            array('id' => '753','state' => 'yobe','state_id' => '36','lg_name' => 'Karasuwa'),
            array('id' => '754','state' => 'yobe','state_id' => '36','lg_name' => 'Machina'),
            array('id' => '755','state' => 'yobe','state_id' => '36','lg_name' => 'Nangere'),
            array('id' => '756','state' => 'yobe','state_id' => '36','lg_name' => 'Nguru'),
            array('id' => '757','state' => 'yobe','state_id' => '36','lg_name' => 'Potiskum'),
            array('id' => '758','state' => 'yobe','state_id' => '36','lg_name' => 'Tarmuwa'),
            array('id' => '759','state' => 'yobe','state_id' => '36','lg_name' => 'Yunusari'),
            array('id' => '760','state' => 'yobe','state_id' => '36','lg_name' => 'Yusufari'),
            array('id' => '761','state' => 'zamfara','state_id' => '37','lg_name' => 'Anka'),
            array('id' => '762','state' => 'zamfara','state_id' => '37','lg_name' => 'Bakura'),
            array('id' => '763','state' => 'zamfara','state_id' => '37','lg_name' => 'Birnin Magaji/Kiyaw'),
            array('id' => '764','state' => 'zamfara','state_id' => '37','lg_name' => 'Bukkuyum'),
            array('id' => '765','state' => 'zamfara','state_id' => '37','lg_name' => 'Bungudu'),
            array('id' => '766','state' => 'zamfara','state_id' => '37','lg_name' => 'Gummi'),
            array('id' => '767','state' => 'zamfara','state_id' => '37','lg_name' => 'Gusau'),
            array('id' => '768','state' => 'zamfara','state_id' => '37','lg_name' => 'Kaura Namoda'),
            array('id' => '769','state' => 'zamfara','state_id' => '37','lg_name' => 'Maradun'),
            array('id' => '770','state' => 'zamfara','state_id' => '37','lg_name' => 'Maru'),
            array('id' => '771','state' => 'zamfara','state_id' => '37','lg_name' => 'Shinkafi'),
            array('id' => '772','state' => 'zamfara','state_id' => '37','lg_name' => 'Talata Mafara'),
            array('id' => '773','state' => 'zamfara','state_id' => '37','lg_name' => 'Chafe'),
            array('id' => '774','state' => 'zamfara','state_id' => '37','lg_name' => 'Zurmi')
        );

        foreach ($lgas as $key => $value) {
            Lga::insert($value);
        }
    }
}
